-- CreateTable
CREATE TABLE `medications` (
    `id` VARCHAR(191) NOT NULL,
    `medicationCode` VARCHAR(191) NOT NULL,
    `genericName` VARCHAR(191) NOT NULL,
    `brandName` VARCHAR(191) NULL,
    `category` VARCHAR(191) NOT NULL,
    `dosageForm` VARCHAR(191) NOT NULL,
    `strength` VARCHAR(191) NOT NULL,
    `unit` VARCHAR(191) NOT NULL,
    `manufacturer` VARCHAR(191) NULL,
    `description` TEXT NULL,
    `indications` TEXT NULL,
    `contraindications` TEXT NULL,
    `sideEffects` TEXT NULL,
    `dosageInstructions` TEXT NULL,
    `pricePerUnit` DECIMAL(10, 2) NOT NULL,
    `stock` INTEGER NOT NULL DEFAULT 0,
    `minStock` INTEGER NOT NULL DEFAULT 5,
    `maxStock` INTEGER NOT NULL DEFAULT 1000,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `requiresPrescription` BOOLEAN NOT NULL DEFAULT true,
    `isControlled` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `createdBy` VARCHAR(191) NULL,

    UNIQUE INDEX `medications_medicationCode_key`(`medicationCode`),
    INDEX `medications_medicationCode_idx`(`medicationCode`),
    INDEX `medications_genericName_idx`(`genericName`),
    INDEX `medications_category_idx`(`category`),
    INDEX `medications_isActive_idx`(`isActive`),
    FULLTEXT INDEX `medications_genericName_brandName_idx`(`genericName`, `brandName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
