const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const medicationSeeder = async () => {
  const medications = [
    // Antibiotics
    {
      medicationCode: 'AMX500',
      genericName: 'Amoxicillin',
      brandName: 'Amoxsan',
      category: 'Antibiotic',
      dosageForm: 'Capsule',
      strength: '500',
      unit: 'mg',
      manufacturer: 'Kimia Farma',
      description: 'Antibiotik untuk mengobati berbagai infeksi bakteri',
      indications: 'Infeksi saluran pernapasan, infeksi kulit, infeksi saluran kemih',
      contraindications: 'Hipersensitif terhadap penisilin',
      sideEffects: 'Mual, muntah, diare, ruam kulit',
      dosageInstructions: '500mg 3x sehari setelah makan',
      pricePerUnit: 2500.00,
      stock: 150,
      minStock: 20,
      maxStock: 300,
      requiresPrescription: true,
      isControlled: false,
    },
    {
      medicationCode: 'CIP500',
      genericName: 'Ciprofloxacin',
      brandName: 'Ciproxin',
      category: 'Antibiotic',
      dosageForm: 'Tablet',
      strength: '500',
      unit: 'mg',
      manufacturer: 'Bayer',
      description: 'Antibiotik spektrum luas golongan fluoroquinolone',
      indications: 'Infeksi saluran kemih, infeksi saluran pencernaan, infeksi kulit',
      contraindications: 'Kehamilan, menyusui, anak-anak',
      sideEffects: 'Pusing, mual, diare, insomnia',
      dosageInstructions: '500mg 2x sehari',
      pricePerUnit: 8500.00,
      stock: 80,
      minStock: 15,
      maxStock: 200,
      requiresPrescription: true,
      isControlled: false,
    },
    {
      medicationCode: 'CEF200',
      genericName: 'Cefixime',
      brandName: 'Cefspan',
      category: 'Antibiotic',
      dosageForm: 'Capsule',
      strength: '200',
      unit: 'mg',
      manufacturer: 'Novartis',
      description: 'Antibiotik sefalosporin generasi ketiga',
      indications: 'Infeksi saluran pernapasan, infeksi saluran kemih',
      contraindications: 'Hipersensitif terhadap sefalosporin',
      sideEffects: 'Diare, mual, sakit kepala',
      dosageInstructions: '200mg 2x sehari',
      pricePerUnit: 12500.00,
      stock: 70,
      minStock: 10,
      maxStock: 140,
      requiresPrescription: true,
      isControlled: false,
    },

    // Analgesics/Pain Relief
    {
      medicationCode: 'PCM500',
      genericName: 'Paracetamol',
      brandName: 'Panadol',
      category: 'Analgesic',
      dosageForm: 'Tablet',
      strength: '500',
      unit: 'mg',
      manufacturer: 'GlaxoSmithKline',
      description: 'Obat penurun demam dan pereda nyeri',
      indications: 'Demam, sakit kepala, nyeri ringan hingga sedang',
      contraindications: 'Gangguan fungsi hati berat',
      sideEffects: 'Jarang terjadi, mual ringan',
      dosageInstructions: '500mg 3-4x sehari',
      pricePerUnit: 500.00,
      stock: 500,
      minStock: 50,
      maxStock: 1000,
      requiresPrescription: false,
      isControlled: false,
    },
    {
      medicationCode: 'IBU400',
      genericName: 'Ibuprofen',
      brandName: 'Brufen',
      category: 'Analgesic',
      dosageForm: 'Tablet',
      strength: '400',
      unit: 'mg',
      manufacturer: 'Abbott',
      description: 'Anti-inflamasi non-steroid untuk mengurangi nyeri dan peradangan',
      indications: 'Nyeri otot, sakit gigi, nyeri haid, demam',
      contraindications: 'Tukak lambung, asma, gangguan ginjal',
      sideEffects: 'Mual, muntah, sakit perut, pusing',
      dosageInstructions: '400mg 3x sehari setelah makan',
      pricePerUnit: 1200.00,
      stock: 200,
      minStock: 25,
      maxStock: 400,
      requiresPrescription: false,
      isControlled: false,
    },
    {
      medicationCode: 'ASP100',
      genericName: 'Aspirin',
      brandName: 'Aspilets',
      category: 'Analgesic',
      dosageForm: 'Tablet',
      strength: '100',
      unit: 'mg',
      manufacturer: 'Unilab',
      description: 'Antiplatelet dan analgesik untuk pencegahan kardiovaskular',
      indications: 'Pencegahan stroke, serangan jantung, nyeri ringan',
      contraindications: 'Tukak lambung, asma, gangguan pembekuan darah',
      sideEffects: 'Iritasi lambung, mual, pusing',
      dosageInstructions: '100mg 1x sehari setelah makan',
      pricePerUnit: 800.00,
      stock: 180,
      minStock: 20,
      maxStock: 350,
      requiresPrescription: false,
      isControlled: false,
    },

    // Cardiovascular
    {
      medicationCode: 'AML5',
      genericName: 'Amlodipine',
      brandName: 'Norvasc',
      category: 'Cardiovascular',
      dosageForm: 'Tablet',
      strength: '5',
      unit: 'mg',
      manufacturer: 'Pfizer',
      description: 'Obat antihipertensi golongan calcium channel blocker',
      indications: 'Hipertensi, angina pektoris',
      contraindications: 'Hipersensitif terhadap amlodipine',
      sideEffects: 'Edema perifer, pusing, kelelahan',
      dosageInstructions: '5mg 1x sehari pagi hari',
      pricePerUnit: 3500.00,
      stock: 120,
      minStock: 20,
      maxStock: 250,
      requiresPrescription: true,
      isControlled: false,
    },
    {
      medicationCode: 'CAP25',
      genericName: 'Captopril',
      brandName: 'Capoten',
      category: 'Cardiovascular',
      dosageForm: 'Tablet',
      strength: '25',
      unit: 'mg',
      manufacturer: 'Bristol-Myers Squibb',
      description: 'ACE inhibitor untuk hipertensi dan gagal jantung',
      indications: 'Hipertensi, gagal jantung',
      contraindications: 'Kehamilan, hiperkalemia',
      sideEffects: 'Batuk kering, hipotensi, ruam kulit',
      dosageInstructions: '25mg 2-3x sehari sebelum makan',
      pricePerUnit: 2800.00,
      stock: 90,
      minStock: 15,
      maxStock: 180,
      requiresPrescription: true,
      isControlled: false,
    },
    {
      medicationCode: 'BIS5',
      genericName: 'Bisoprolol',
      brandName: 'Concor',
      category: 'Cardiovascular',
      dosageForm: 'Tablet',
      strength: '5',
      unit: 'mg',
      manufacturer: 'Merck',
      description: 'Beta blocker untuk hipertensi dan gagal jantung',
      indications: 'Hipertensi, gagal jantung, angina',
      contraindications: 'Asma, bradikardia, syok kardiogenik',
      sideEffects: 'Bradikardia, kelelahan, pusing',
      dosageInstructions: '5mg 1x sehari pagi hari',
      pricePerUnit: 5200.00,
      stock: 60,
      minStock: 10,
      maxStock: 120,
      requiresPrescription: true,
      isControlled: false,
    },

    // Gastrointestinal
    {
      medicationCode: 'OME20',
      genericName: 'Omeprazole',
      brandName: 'Losec',
      category: 'Gastrointestinal',
      dosageForm: 'Capsule',
      strength: '20',
      unit: 'mg',
      manufacturer: 'AstraZeneca',
      description: 'Proton pump inhibitor untuk mengurangi asam lambung',
      indications: 'Tukak lambung, GERD, dispepsia',
      contraindications: 'Hipersensitif terhadap omeprazole',
      sideEffects: 'Sakit kepala, mual, diare, konstipasi',
      dosageInstructions: '20mg 1x sehari sebelum makan pagi',
      pricePerUnit: 4200.00,
      stock: 100,
      minStock: 20,
      maxStock: 200,
      requiresPrescription: true,
      isControlled: false,
    },
    {
      medicationCode: 'DOM10',
      genericName: 'Domperidone',
      brandName: 'Motilium',
      category: 'Gastrointestinal',
      dosageForm: 'Tablet',
      strength: '10',
      unit: 'mg',
      manufacturer: 'Janssen',
      description: 'Obat anti mual dan muntah',
      indications: 'Mual, muntah, kembung',
      contraindications: 'Perforasi gastrointestinal, obstruksi usus',
      sideEffects: 'Mulut kering, sakit kepala, diare',
      dosageInstructions: '10mg 3x sehari sebelum makan',
      pricePerUnit: 1500.00,
      stock: 150,
      minStock: 25,
      maxStock: 300,
      requiresPrescription: false,
      isControlled: false,
    },
    {
      medicationCode: 'RAN150',
      genericName: 'Ranitidine',
      brandName: 'Zantac',
      category: 'Gastrointestinal',
      dosageForm: 'Tablet',
      strength: '150',
      unit: 'mg',
      manufacturer: 'GSK',
      description: 'H2 receptor antagonist untuk mengurangi asam lambung',
      indications: 'Tukak lambung, GERD, dispepsia',
      contraindications: 'Hipersensitif terhadap ranitidine',
      sideEffects: 'Sakit kepala, pusing, konstipasi',
      dosageInstructions: '150mg 2x sehari',
      pricePerUnit: 2800.00,
      stock: 80,
      minStock: 15,
      maxStock: 160,
      requiresPrescription: false,
      isControlled: false,
    },

    // Respiratory
    {
      medicationCode: 'SAL2',
      genericName: 'Salbutamol',
      brandName: 'Ventolin',
      category: 'Respiratory',
      dosageForm: 'Inhaler',
      strength: '100',
      unit: 'mcg/puff',
      manufacturer: 'GlaxoSmithKline',
      description: 'Bronkodilator untuk mengatasi sesak napas',
      indications: 'Asma, PPOK, bronkospasme',
      contraindications: 'Hipersensitif terhadap salbutamol',
      sideEffects: 'Tremor, palpitasi, sakit kepala',
      dosageInstructions: '2 puff saat sesak napas, maksimal 8 puff/hari',
      pricePerUnit: 45000.00,
      stock: 30,
      minStock: 5,
      maxStock: 60,
      requiresPrescription: true,
      isControlled: false,
    },
    {
      medicationCode: 'CTM4',
      genericName: 'Chlorpheniramine',
      brandName: 'CTM',
      category: 'Respiratory',
      dosageForm: 'Tablet',
      strength: '4',
      unit: 'mg',
      manufacturer: 'Kimia Farma',
      description: 'Antihistamin untuk mengatasi alergi',
      indications: 'Rinitis alergi, urtikaria, alergi kulit',
      contraindications: 'Glaukoma, hipertrofi prostat',
      sideEffects: 'Kantuk, mulut kering, pusing',
      dosageInstructions: '4mg 3x sehari',
      pricePerUnit: 400.00,
      stock: 300,
      minStock: 40,
      maxStock: 600,
      requiresPrescription: false,
      isControlled: false,
    },

    // Diabetes
    {
      medicationCode: 'MET500',
      genericName: 'Metformin',
      brandName: 'Glucophage',
      category: 'Antidiabetic',
      dosageForm: 'Tablet',
      strength: '500',
      unit: 'mg',
      manufacturer: 'Merck',
      description: 'Obat diabetes tipe 2 golongan biguanide',
      indications: 'Diabetes mellitus tipe 2',
      contraindications: 'Gagal ginjal, asidosis metabolik',
      sideEffects: 'Mual, diare, sakit perut, rasa metalik',
      dosageInstructions: '500mg 2x sehari dengan makanan',
      pricePerUnit: 1800.00,
      stock: 180,
      minStock: 30,
      maxStock: 350,
      requiresPrescription: true,
      isControlled: false,
    },
    {
      medicationCode: 'GLI5',
      genericName: 'Glimepiride',
      brandName: 'Amaryl',
      category: 'Antidiabetic',
      dosageForm: 'Tablet',
      strength: '2',
      unit: 'mg',
      manufacturer: 'Sanofi',
      description: 'Sulfonilurea untuk diabetes tipe 2',
      indications: 'Diabetes mellitus tipe 2',
      contraindications: 'Diabetes tipe 1, ketoasidosis diabetik',
      sideEffects: 'Hipoglikemia, mual, sakit kepala',
      dosageInstructions: '2mg 1x sehari sebelum sarapan',
      pricePerUnit: 3200.00,
      stock: 100,
      minStock: 15,
      maxStock: 200,
      requiresPrescription: true,
      isControlled: false,
    },

    // Vitamins & Supplements
    {
      medicationCode: 'VITB12',
      genericName: 'Cyanocobalamin',
      brandName: 'Neurobion',
      category: 'Vitamin',
      dosageForm: 'Tablet',
      strength: '500',
      unit: 'mcg',
      manufacturer: 'Merck',
      description: 'Vitamin B12 untuk kesehatan saraf',
      indications: 'Defisiensi vitamin B12, neuropati',
      contraindications: 'Hipersensitif terhadap cobalamin',
      sideEffects: 'Jarang terjadi, reaksi alergi ringan',
      dosageInstructions: '1 tablet 1x sehari',
      pricePerUnit: 2200.00,
      stock: 200,
      minStock: 30,
      maxStock: 400,
      requiresPrescription: false,
      isControlled: false,
    },
    {
      medicationCode: 'VITC500',
      genericName: 'Ascorbic Acid',
      brandName: 'Redoxon',
      category: 'Vitamin',
      dosageForm: 'Tablet',
      strength: '500',
      unit: 'mg',
      manufacturer: 'Bayer',
      description: 'Vitamin C untuk meningkatkan daya tahan tubuh',
      indications: 'Defisiensi vitamin C, meningkatkan imunitas',
      contraindications: 'Batu ginjal oksalat',
      sideEffects: 'Mual, kram perut, batu ginjal (dosis tinggi)',
      dosageInstructions: '500mg 1x sehari',
      pricePerUnit: 800.00,
      stock: 300,
      minStock: 50,
      maxStock: 600,
      requiresPrescription: false,
      isControlled: false,
    },
    {
      medicationCode: 'VITD1000',
      genericName: 'Cholecalciferol',
      brandName: 'Ossoral',
      category: 'Vitamin',
      dosageForm: 'Tablet',
      strength: '1000',
      unit: 'IU',
      manufacturer: 'Sanofi',
      description: 'Vitamin D3 untuk kesehatan tulang',
      indications: 'Defisiensi vitamin D, osteoporosis',
      contraindications: 'Hiperkalsiuria, batu ginjal kalsium',
      sideEffects: 'Mual, konstipasi, sakit kepala',
      dosageInstructions: '1000 IU 1x sehari',
      pricePerUnit: 1500.00,
      stock: 150,
      minStock: 20,
      maxStock: 300,
      requiresPrescription: false,
      isControlled: false,
    },

    // Antacids
    {
      medicationCode: 'ALH200',
      genericName: 'Aluminum Hydroxide',
      brandName: 'Mylanta',
      category: 'Antacid',
      dosageForm: 'Suspension',
      strength: '200',
      unit: 'mg/5ml',
      manufacturer: 'Johnson & Johnson',
      description: 'Antasida untuk mengatasi kelebihan asam lambung',
      indications: 'Gastritis, dispepsia, tukak lambung',
      contraindications: 'Obstruksi usus, gangguan ginjal berat',
      sideEffects: 'Konstipasi, mual',
      dosageInstructions: '5-10ml 3x sehari setelah makan',
      pricePerUnit: 15000.00,
      stock: 60,
      minStock: 10,
      maxStock: 120,
      requiresPrescription: false,
      isControlled: false,
    },

    // Controlled Medications
    {
      medicationCode: 'TRM50',
      genericName: 'Tramadol',
      brandName: 'Tramal',
      category: 'Analgesic',
      dosageForm: 'Capsule',
      strength: '50',
      unit: 'mg',
      manufacturer: 'Grünenthal',
      description: 'Analgesik opioid untuk nyeri sedang hingga berat',
      indications: 'Nyeri sedang hingga berat',
      contraindications: 'Intoksikasi alkohol, depresi pernapasan',
      sideEffects: 'Pusing, mual, konstipasi, kantuk',
      dosageInstructions: '50mg setiap 6-8 jam sesuai kebutuhan',
      pricePerUnit: 3500.00,
      stock: 50,
      minStock: 5,
      maxStock: 100,
      requiresPrescription: true,
      isControlled: true,
    },
    {
      medicationCode: 'MOR10',
      genericName: 'Morphine',
      brandName: 'MST',
      category: 'Analgesic',
      dosageForm: 'Tablet',
      strength: '10',
      unit: 'mg',
      manufacturer: 'Mundipharma',
      description: 'Analgesik opioid kuat untuk nyeri berat',
      indications: 'Nyeri berat, kanker',
      contraindications: 'Depresi pernapasan, ileus paralitik',
      sideEffects: 'Sedasi, depresi pernapasan, konstipasi, mual',
      dosageInstructions: '10mg setiap 8-12 jam',
      pricePerUnit: 15000.00,
      stock: 20,
      minStock: 2,
      maxStock: 50,
      requiresPrescription: true,
      isControlled: true,
    },

    // Topical
    {
      medicationCode: 'HYC1',
      genericName: 'Hydrocortisone',
      brandName: 'Kenacort',
      category: 'Topical',
      dosageForm: 'Cream',
      strength: '1',
      unit: '%',
      manufacturer: 'Novartis',
      description: 'Kortikosteroid topikal untuk peradangan kulit',
      indications: 'Dermatitis, eksim, psoriasis',
      contraindications: 'Infeksi virus, bakteri, jamur pada kulit',
      sideEffects: 'Iritasi kulit, penipisan kulit',
      dosageInstructions: 'Oleskan tipis 2-3x sehari pada area yang terkena',
      pricePerUnit: 12000.00,
      stock: 40,
      minStock: 8,
      maxStock: 80,
      requiresPrescription: true,
      isControlled: false,
    },
    {
      medicationCode: 'BET05',
      genericName: 'Betamethasone',
      brandName: 'Celestoderm',
      category: 'Topical',
      dosageForm: 'Cream',
      strength: '0.05',
      unit: '%',
      manufacturer: 'Schering-Plough',
      description: 'Kortikosteroid topikal poten untuk peradangan kulit',
      indications: 'Dermatitis, psoriasis, eksim',
      contraindications: 'Infeksi kulit, rosacea, dermatitis perioral',
      sideEffects: 'Atrofi kulit, striae, telangiektasia',
      dosageInstructions: 'Oleskan tipis 1-2x sehari',
      pricePerUnit: 18000.00,
      stock: 25,
      minStock: 5,
      maxStock: 50,
      requiresPrescription: true,
      isControlled: false,
    }
  ];

  try {
    // Clear existing medications if needed
    console.log('  🗑️ Clearing existing medications...');
    await prisma.medication.deleteMany({});

    // Create medications using createMany for better performance
    const result = await prisma.medication.createMany({
      data: medications,
      skipDuplicates: true,
    });

    console.log(`  ✅ Successfully created ${result.count} medications`);

    // Log statistics
    const stats = {
      total: await prisma.medication.count(),
      prescriptionOnly: await prisma.medication.count({ where: { requiresPrescription: true } }),
      controlled: await prisma.medication.count({ where: { isControlled: true } }),
      byCategory: await prisma.medication.groupBy({
        by: ['category'],
        _count: { id: true },
      }),
    };

    console.log(`  📊 Medication Statistics:`);
    console.log(`     Total: ${stats.total}`);
    console.log(`     Prescription Only: ${stats.prescriptionOnly}`);
    console.log(`     Controlled: ${stats.controlled}`);
    console.log(`     By Category:`);
    stats.byCategory.forEach(cat => {
      console.log(`       ${cat.category}: ${cat._count.id}`);
    });

  } catch (error) {
    console.error('  ❌ Error seeding medications:', error);
    throw error;
  }
};

module.exports = medicationSeeder;